# Use official Node.js image as base
FROM node:20-alphine

# Set working directory
WORKDIR /app

# COPY package.json and package-lock.json to the working directory
COPY package*.json./

# Install  the application dependencies
RUN npm install

# Copy the application code to the working directory
COPY . .

# Build the application
RUN npm run build


# Expose  the port on which the application will run
EXPOSE 5173

# Set the command to start the application
CMD ["npm", "run", "preview"]
